highlight Comment ctermbg=0 ctermfg=7
highlight String ctermbg=0 ctermfg=6
highlight Character ctermbg=0 ctermfg=3
highlight Number ctermbg=0 ctermfg=1
highlight Boolean ctermbg=0 ctermfg=1
highlight Float ctermbg=0 ctermfg=1
highlight Function ctermbg=0 ctermfg=4
highlight Statement ctermbg=0 ctermfg=5
highlight Operator ctermbg=0 ctermfg=5
highlight Type ctermbg=0 ctermfg=5
highlight PreProc ctermbg=0 ctermfg=5
highlight Keyword ctermbg=0 ctermfg=6
highlight LineNr ctermbg=0 ctermfg=7
